file=$1

echo "// NOTE : This file is now auto-generated by app/automatic-index.bash when you compile the build using 'make'."
echo "// 	See the file app/include-list.txt to adjust which modules should be included in the build, and which"
echo "//	should serve as dependencies."

cat $file | awk  '($1 ~ /^module/) && !($2 ~ /^no-export/){printf "import %s from \"../%s\" \n", $2, $3}; NF==0{print " "}'


cat $file | awk '($1 ~ /^module/) && !($2 ~ /^no-export/)' | awk 'BEGIN {
	print "export {"
}{
    if (NR>1) {
        # process str
        printf("\t%s,\n", str);
    }
    str=$2;
}
END {
    # process whatever needed before printing the last line and then print the last line.
    printf( "\t%s\n", str);
    print "}";
}'
